### ISSUE TITLE
Crashes on iOS 10.3

### ISSUE THREAD

**Issue by burabure** [es-shims/Promise.prototype.finally#7]
I don't have many details because I don't have iDevices but a teammate had to remove the polyfill because it's crashing on iOS 10.3

![image](https://cloud.githubusercontent.com/assets/3132298/25723188/6bba12fc-30ed-11e7-9a8d-b1affa2054d0.png)

on iOS 10.2 this doesn't happen and the polyfill works without any issues

**Comment by ljharb** [comment]
@burabure are you using babel-polyfill by chance?

**Comment by burabure** [comment]
yes, is there a known issue?

**Comment by ljharb** [comment]
This seems similar to #5.

Can you provide me a repro case? I can use browserstack to test it on iOS.

**Comment by burabure** [comment]
It should be easy to repro. I think something simple like this should do it:
```js
Promise.resolve(true).finally(() => 'this should fail')
```

**Comment by ljharb** [comment]
I'd also need the script tags that led to that failing - ie, including core-js via babel-polyfill, and this lib, and in which order you include them.

**Comment by burabure** [comment]
```html
    ...
    <script src="vendor.js"></script>
    <script defer src="apps.js"></script>
</body>
```

vendor contains all the core-js and babel-polyfill stuff, app.js contains the app stuff + polyfill

**Comment by ljharb** [comment]
hopefully this polyfill runs first inside `apps.js`?

**Comment by ljharb** [comment]
Also, which version of babel-polyfill and core-js are you using?

**Comment by burabure** [comment]
```js
babel-core": "^6.22.1",
"babel-plugin-transform-runtime": "^6.12.0",
"babel-polyfill": "^6.13.0",
"babel-runtime": "^6.11.6",
```

**Comment by ekeric13** [comment]
Also having issues on 10.3 and Firefox 57.

Importing Promise.prototype.finally via babel-polyfill (which imports promise.finally via core-js).

```
"babel-core": "^6.4.0",
"babel-polyfill": "^6.26.0",
"babel-preset-env": "^1.6.1",
"babel-preset-stage-0": "^6.16.0",
```

.babelrc:
```
    "dev": {
      "presets": [
        ["env", {
          "targets": {
            "browsers": [
              "ios >= 10",
              "safari >= 10",
              "chrome >= 60",
              "edge >= 15",
              "firefox >= 55"
            ],
            "uglify": true
          },
          "modules": false,
          "useBuiltIns": true
        }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "transform-decorators-legacy"
      ]
    },
```

At the beginning of my app bundle I just do
`import babel-polyfill`

```
    return axios
      .post(url)
      .then(res => {
        //stuff
      })
	.catch((err)=>{
       // stuff
     })
      .finally(() => {
        //stuff
      });
```

error: `TypeError: undefined is not a function (near '...].done())})).finally(Object(o["action"])...')`

**Comment by ljharb** [comment]
@ekeric13 Firefox isn't available on iOS; this issue is about iOS. Perhaps you could move your comment to #15 or #13?

**Comment by ekeric13** [comment]
To be clear, .finally is not working in both firefox **and** ios 10.3. The error I posted was specific to it .finally not working on ios 10.3. So I think that is most relevant to this issue thread.

**Comment by ljharb** [comment]
Ah, thanks for clarifying.

@ekeric13 this shim is *not* part of core-js; babel-polyfill does not include it. To be relevant to this repo, you need to explicitly import `promise.prototype.finally` and invoke its `shim` method. If it's solely broken with babel-polyfill, you'll need to file a bug on core-js.

**Comment by ekeric13** [comment]
@ljharb Hmm. I thought it might have been related to this shim since I am having issues in the same exact browsers that other users are having. 

I will go ahead and delete my comments. 

To clarify further, this library did help me resolve my issue by importing it above the main polyfill I am using:

```
import shim from 'promise.prototype.finally/shim';
shim();
import 'babel-polyfill';
```

**Comment by ljharb** [comment]
Closing, since this continues to lack a repro.

If anyone can provide a codesandbox or jsfiddle link that crashes - on any engine - I'd be happy to reopen and fix it.
